import Head from "next/head";
import styles from "@/styles/Home.module.css";
import Navbar from "../Components/Navbar/Navbar";
import Home from "@/Sections/Home/Home";
import Experiences from "@/Sections/Experiences/Experiences";


export default function App() {
  return (
    <>
      <Head>
        <title>Olivier tebar</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <div className={styles.container}>
        <Navbar />
        <Home />
        <Experiences />
      </div>
    </>
  );
}
